#COLAB 설정

google drive mount  
google drive를 colab환경에 mount해서 colab에서 파일을 읽고 쓸수 있도록 설정

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

In [4]:
import os
print(os.getcwd())
print(os.listdir())

/content
['.config', 'sample_data']

# NUMPY 실습

In [2]:
import numpy as np

Ndarray  
numpy.array()함수에 list like형태의 데이터를 입력하여 생성한다.  
doc: https://compmath.korea.ac.kr/appmath/NumpyBasics.html

In [3]:
data = [1,2,3]
print(type(data))

np_array = np.array(data)
print(type(np_array))

<class 'list'>
<class 'numpy.ndarray'>

Ndarray는 행렬 형태의 데이터   
행렬은 각 행과 열에 데이터의 크기가 같아야한다.

python의 list는 단순 데이터의 묶음 형태이기 때문에 [[1,2],1,(1,2,3)] 같이 각 element의 형태, 크기, 타입이 자유로움   
numpy의 ndarray는 행렬, 텐서와 같은형태를 가지기 때문에 각 elements의 타입이 동일해야하며 모든 열과 행의 크기가 같아야 함

In [6]:
l = [[1,2],1,(1,2,3), 'str']
np_array = np.array(l) # error

l = [[1,2,3], [1,2,3]]
a = np.array(l)
print(a.shape)

(2, 3)

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:2: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.

ndarray는 상수와의 연산, ndarray와의 연산, 행렬연산 등 다양한 연산을 지원한다.

In [ ]:
# 놓침

#Pandas

DB를 파이썬에서 쉽게 처리할 수 있도록 하는 패키지

Dataframe을 통해 table형태의 데이터를 쉽게 다룰 수 있게 하며  
대표적인 table형태의 데이터인 xlsx, csv와 같은 데이터를 쉽게 load

In [ ]:
import pandas as pd

pd.read_csv()